"""Initial clean migration

Revision ID: 617048246dd0
Revises: 
Create Date: 2025-09-13 12:49:11.698724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617048246dd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping _alembic_tmp_backup_report if it doesn't exist
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    if '_alembic_tmp_backup_report' in tables:
        op.drop_table('_alembic_tmp_backup_report')
    
    # Only alter backup_report if it exists
    if 'backup_report' in tables:
        with op.batch_alter_table('backup_report', schema=None) as batch_op:
            batch_op.alter_column('date',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.String(length=100),
                   nullable=True)
            batch_op.alter_column('type',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.String(length=100),
                   nullable=True)
            batch_op.alter_column('result',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.String(length=100),
                   nullable=True)
            batch_op.alter_column('size',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.String(length=100),
                   nullable=True)

    # Only alter credential if it exists
    if 'credential' in tables:
        with op.batch_alter_table('credential', schema=None) as batch_op:
            batch_op.add_column(sa.Column('password', sa.String(length=100), nullable=True))
            batch_op.drop_column('password_encrypted')

    # Only alter custom_field if it exists
    if 'custom_field' in tables:
        with op.batch_alter_table('custom_field', schema=None) as batch_op:
            batch_op.alter_column('form_name',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.String(length=100),
                   existing_nullable=True)

    # Only alter custom_value if it exists
    if 'custom_value' in tables:
        with op.batch_alter_table('custom_value', schema=None) as batch_op:
            batch_op.drop_constraint(None, type_='foreignkey')

    # Only alter server if it exists
    if 'server' in tables:
        with op.batch_alter_table('server', schema=None) as batch_op:
            batch_op.alter_column('name',
                   existing_type=sa.VARCHAR(length=100),
                   nullable=True)
            batch_op.alter_column('ip_address',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.String(length=100),
                   nullable=True)
            batch_op.alter_column('os_type',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.String(length=100),
                   nullable=True)
            batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.String(length=100),
                   nullable=True)

    # Only alter task if it exists
    if 'task' in tables:
        with op.batch_alter_table('task', schema=None) as batch_op:
            batch_op.alter_column('title',
                   existing_type=sa.VARCHAR(length=100),
                   nullable=True)
            batch_op.alter_column('description',
                   existing_type=sa.VARCHAR(length=200),
                   nullable=True)
            batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.String(length=100),
                   nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('os_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('custom_value', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'custom_field', ['field_id'], ['id'])

    with op.batch_alter_table('custom_field', schema=None) as batch_op:
        batch_op.alter_column('form_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_encrypted', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('password')

    with op.batch_alter_table('backup_report', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('result',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               nullable=False)

    op.create_table('_alembic_tmp_backup_report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=100), nullable=True),
    sa.Column('type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('result', sa.VARCHAR(length=100), nullable=True),
    sa.Column('size', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
